[simulation]
on              = 1                                                                     #necessary
input_dir       = "tests/data/idefix_1_dust_fluid"                                      #necessary
unit_length_au  = 93.0                                                                  #necessary
unit_mass_msun  = 1.2                                                                   #necessary
component       = ["dust", "gas"]                                                       #necessary
internal_rho    = 2.0                                                                   #necessary if dust
mask_inside     = 1.2                                                                   #optional

[prodimo]
from            = "tests/data/idefix_1_dust_fluid/prodimo_from_ref"                     #necessary
to              = "example/prodimo_to"                                                  #necessary
plot            = true                                                                  #optional
